### PR TITLE
Generate wolfram.clj with vars for Wolfram symbols

### LINKED ISSUE #33: Find out if we can get autocomplete support with loaded Wolf symbols in Calva/Cursive/Emacs
`load-all-symbols` creates vars with docs in a namespace. But none of Cursive/kondo/Calva seems to "see" these and use them for autocompletion. Can we do anything to help them? Autocompl. would be helpful for UX.

### PR DESCRIPTION
**Pull request by holyjak**
* Introduce wolframite.impl.wolfram-syms.* for dealing with interning wolfram symbols, move intern and load-syms there
* Add ...write ns to write wolframite/wolfram.clj with defs of the loaded symbols (to be included in git and used as a starting point by users, unless they decide to re-write it)

Fixes #33, #45, #53

### CODE REVIEW

**Comment by holyjak** [comment]
# FIXME Lambdas don't work

`(wl/eval (w/Map (fn [x] (w/+ x 1)) [1 2 3]))` and rewriting `(wl/eval '(Function [x] (StringJoin "Hello, " x "! This is a Mathematica function's output.")))` to use `fn` and w/StringJoin does not work. The lambda fn does not correctly translate its body back to symbols, so in the first wecase we end up with a vector of 3 lambda fn names instead of nums.

**Comment by holyjak** [comment]
# TODO


Update the docs, mention how to re-create the w ns

**Comment by light-matters** [comment]
Thoughts on kernel-info!

As far as I can see it's not side-affecting and so shouldn't have an exclamation mark?
Since it's just returning data on the system then it goes well with similar functions in runtime.system (rather than in core)?

**Comment by light-matters** [comment]
- Working through the getting started seems to work.
- Docstrings appear in emacs minibuffer while typing out functions (w/N w/PI) etc.
- 'normal' autocompletion didn't seem to work, but after some delay (I was on the phone for five minutes) it seems to work well.

**Comment by light-matters** [comment]
I really like that I can now do things like

```clojure
 (-> 'x
    (w/Integrate 'x)
    wl/eval)
```

**Pull request merged**
