### PR TITLE
Fix #111: wl/start etc return value

### LINKED ISSUE #111: wl/start (and restart etc.) and package loads should return a value on success
It might be better for wl/start and wl/restart to return a value, e.g. :ok, :started, :success, :restarted or a welcome string to communicate positively with the user. 

This would be less ambiguous than 'nil'.

### PR DESCRIPTION
**Pull request by holyjak**
Issue: An inexperienced user may not know what the return value of nil means.

Fix: Be explicit and return a map with `:status :ok` and perhaps additional info. E.g. wolfram version seems useful.

### CODE REVIEW

**Comment by holyjak** [comment]
TODO: package

**Comment by light-matters** [comment]
Works well at my end. I had to do the tests manually though as there seems to be something wrong with the namespace detection (probably an Emacs setup bug).

How do you feel about adding an exclamation mark to the end of start,restart etc. though? I know that last time it was deemed unnecessary, but somehow I miss the consistency with side-affecting operations.

**Comment by holyjak** [comment]
No strong feelings here. If you really want it, we can change it. Will need to update docs...

**Comment by light-matters** [comment]
Let's do it. I know it seems like an awkward use of time, but it would help my mild OCD :).

**Comment by light-matters** [comment]
I can do it later or tomorrow morning.

**Comment by holyjak** [comment]
just remember to run tests and build site on this branch, before merging...

**Comment by holyjak** [comment]
I do not like `eval!`. Yes, it is side-effecting, since it can set global vars in Wolfram. But it seems too extreme to have ! there. It is st. else then starting/stopping an external process, as start! does...

**Comment by light-matters** [comment]
> I do not like `eval!`. Yes, it is side-effecting, since it can set global vars in Wolfram. But it seems too extreme to have ! there. It is st. else then starting/stopping an external process, as start! does...

Yep, I thought it was more controversial and I hesitated, but made it a separate commit to make it easy to remove. I don't really see the problem with it, but it's true that it's not always side-affecting. Ironically, I would like to find a shorter way to call it and I was thinking that using wl/! as an alternative to eval would be more ergonomic when playing with different expressions. 

In other news, I'm having trouble with running the tests so it might be quicker for you to check that I didn't mess anything up with start! etc.

**Comment by light-matters** [comment]
Think that's it reset.

**Comment by light-matters** [comment]
tests and website seem to run, but I discovered a bug (in the public site) that I'll post an issue for.

**Pull request merged**
