### PR TITLE
[Enhancement] Include custom aliases in generated wolfram ns

### LINKED ISSUE #59: More powerful aliasing (perhaps as an extended wolfram.clj)
Currently, simple function aliasing (1->1 swaps) can be added at runtime by passing the aliases either to the 'init!' function or to a given 'eval'.

More powerful aliases (Such as the experimental fn aliases explored in #58) would also be useful though. 

This poses a problem however, as using the generated wolfram.clj namespace for wolframite-only aliases would potentially be confusing. One option would be to generate two wolfram.clj-like namespaces. One for the default wolfram definitions and functions (already adapted to map complicated things like Minus and Subtract)  and one that extends this namespace with a series of UX-enhancing aliases. This could have plausibly useful defaults, but could also be extended by the user.

An example of simple aliases that would help usability and readability.
```clojure
{
   '<-> 'ReplaceAll
   '** 'Power

'**2 'WolframitePower2
   '**3 'WolframitePower3
   '**4 'WolframitePower4
   '**5 'WolframitePower5
   '**6 'WolframitePower6
   '**7 'WolframitePower7
   '**8 'WolframitePower8
   '**9 'WolframitePower9

   '**-1 'WolframitePowerMinus1
   '**-2 'WolframitePowerMinus2
   '**-3 'WolframitePowerMinus3
   '**-4 'WolframitePowerMinus4
   '**-5 'WolframitePowerMinus5
   '**-6 'WolframitePowerMinus6
   '**-7 'WolframitePowerMinus7
   '**-8 'WolframitePowerMinus8
   '**-9 'WolframitePowerMinus9}
```
A really interesting usecase however, would be to take advantage of clojure's native unicode support and so greatly expand the number of symbols that could be inserted and processed directly. 

Some examples could be the greek and hebrew alphabets as well as things like
```clojure
   '⮾ 'NonCommutativeMultiply
   '√ 'Sqrt
   '∫ 'Integrate
```
.

This could greatly help the usability and readability of mathematical working.

### PR DESCRIPTION
**Pull request by holyjak**
Issue: `wl/init!` / `wl/eval` make it possible to teach Wolfram about custom aliases, but they only work in the symbolic form, i.e. `(list '<the symbol> args...)`. It would be more convenient to have function vars for this as we do for the built-in aliases such as `*`, so that the user could do `(w/<the symbol> args...)`.

Fix: Extend write-ns! to take a map of opts, including aliases, and write these to the file.

Fixes #59 partly.

### CODE REVIEW

**Comment by light-matters** [comment]
Having trouble getting this to work. I'll post a more detailed comment soon, but I can write a file that doesn't get used at the moment...

**Comment by holyjak** [comment]
To test:

```clj
clj -Sdeps '{:deps {s/w {:local/root "/Users/holyjak/Projects/external/scicloj/wolframite/target/wolframite-1.0.0-SNAPSHOT.jar"} org.clojure/clojure {:mvn/version "1.12.0-alpha12"}}}'

user=> (require '[wolframite.core :as wl] '[wolframite.impl.wolfram-syms.write-ns :as wns])
user=> (wl/init!)
user=> (wns/write-ns! "/tmp/wolf1.clj")
nil
user=> (load-file "/tmp/wolf1.clj")
#'wolframite.wolfram/fn
```

This works for me. 

Noteworthy: the file and the ns it declares may be out of sync, as it is in this case. But the write should still work, and so the load.

**Comment by light-matters** [comment]
Ah, I think I understand what's happening now. It was a combination of wrong assumptions, but this might be useful for the sake of other users who are as dim as me.

 I naturally (and wrongly) assumed that using write-ns! would remove the need to also pass the aliases to init!. I also wrongly assumed (though quickly realised my mistake)  that init! could be rerun with different arguments without changing the REPL. 

Other things to note:
- namespace name should be generated from the path (different filename will not have different namespace)?
- default run on import will not work unless you have the same directory structure

**Comment by holyjak** [comment]
As always, users never read docs(trings) ;-)

> namespace name should be generated from the path (different filename will not have different namespace)? 

Ideally yes, but I'd leave that for later. Ppl can always refactor this.

> default run on import will not work unless you have the same directory structure

WDYM?

**Comment by light-matters** [comment]
> As always, users never read docs(trings) ;-)
Lol, guilty. In my slight defense, I read the doc entry on the README and the first line of the docstring... :)

> > default run on import will not work unless you have the same directory structure
> 
> WDYM?
I mean that if you use wolframite as a library and import it then a default run of write-ns! will almost always fail with an error (assuming that you don't have wolframite as a parent directory). I'm thinking that the default arg is only good for wolframite developers unless we want to automatically create the parent directory using fs?
```clojure
([] (write-ns! "src/wolframite/wolfram.clj"))
...
```

**Comment by holyjak** [comment]
Perhaps we should rather drop the no-arg arity and force users to supply a path?

**Comment by light-matters** [comment]
> Perhaps we should rather drop the no-arg arity and force users to supply a path?

I think that's probably the cleanest for now. I do like the idea of having a sensible default, but if we're going for usability then the namespace should be automatically chosen (discussed above) and probably we shouldn't have to specify the aliases twice. These seem like a job for another version though.

**Comment by light-matters** [comment]
I'll make a commit and then merge.

**Pull request merged**
