### PR TITLE
[Fix #118] Display Video output with Kindly

### LINKED ISSUE #118: Support Video display
Manipulating/creating a Wolfram `Video` returns a strange format that no visual tool knows how to interpret.

```clojure
(w/VideoTrim [12 24])
```
Returns 
```clojure
(Video /home/ctw/Documents/Wolfram/Video/VideoTrim-5ef8ad95-051d-4e6f-a1b2-1f1e24b62217.mkv (-> Appearance Automatic) (-> AudioOutputDevice Automatic) (-> SoundVolume Automatic))
```
We should some implement some sort of 'kindly' support  (e.g. metadata) that allows visual tools such as Clay and Clerk to display these outputs correctly.

### PR DESCRIPTION
**Pull request by holyjak**
Issue: Wolfram may return `(Video <path to file> ...)` and we want to be able to display it nicely in a Clay or compatible notebook.

Fix: Add ns with a fn to try add display metadata to all results, call it from eval.

### CODE REVIEW

**Comment by light-matters** [comment]
This is not currently working for me.

**Comment by light-matters** [comment]
I am first struggling to display any video with kindly and also because VideoTrim returns a slightly different format. I'm working on the first issue first though.

**Comment by light-matters** [comment]
The format `(k/video {:src "./resources/video/Baby.mp4"})` works for me rather than file://...

**Comment by light-matters** [comment]
We would also need to somehow specify the default path to Wolfram video operations (~/Documents/Wolfram/Video) or add the folder dynamically.

**Comment by light-matters** [comment]
```clojure
(defn- kind<-Video
  "Takes a Wolfram-like `(video url ...)` expression and returns an appropriate video kind.

  NOTE: Take care with the capital letter. This is to distinguish a Wolfram `Video` from other types."
  [expr]
  (k/video {:src (second expr)}))

(defn maybe-add-kindly-meta [expr]
  {:pre [expr]}
  (if (instance? IObj expr)
    (cond
      (= (head expr) 'Video)
      (k/fn expr
        {:kindly/f kind<-Video}))

    expr))
```

Seems to work for me for a 'normal' `(Video ...)`. Not sure why it's not working for the output of `VideoTrim` though.

**Comment by light-matters** [comment]
Interestingly, 

```clojure
(-> (w/do (-> "./resources/video/Baby.mp4"
              w/Video
              (w/VideoTrim [6 7])
              (->> (w/= 'thing)))
          (-> 'thing))
    wl/eval) ;; => doesn't work

(-> "./resources/video/Baby.mp4"
    w/Video
    (w/VideoTrim [6 7])
    (->> (w/= 'thing))
    wl/eval)

(-> 'thing
    wl/eval) ;; => does work!


```

**Comment by holyjak** [comment]
I bet  ☝️works because the latter returns whatever `=` returns, which is the RHS, which is the VideoTrim output. But the former could also be simplified to two calls `(wl/eval ...)`  `(wl/eval 'thing)` and then it is perhaps not surprising it only returns `'thing`.

**Pull request merged**
